name: Terraform Plan

on:
  workflow_run:
    workflows: [ "Update Docker Image" ]
    types: [ completed ]
    branches: [ master ]

jobs:
 lint:
   name: Lint
   runs-on: ubuntu-latest
   if: ${{ github.event.workflow_run.conclusion == 'success' }}
   steps:
     - name: Check out code
       uses: actions/checkout@v2
 
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
         terraform_version: 1.3.3
 
     - name: Run terraform fmt check
       run: terraform fmt -check -diff -recursive
 
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-region: us-east-1
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
     - name: Initialize Terraform
       run: |
         cd terraform/
         terraform init -input=false         
 
     - name: Plan Terraform
       id: plan
       continue-on-error: true
       run: |
         cd terraform/
         terraform plan -input=false -no-color
         
     - name: Terraform Apply
       run: |
        cd terraform/
        terraform apply -auto-approve -input=false
